development: &non_production_settings
  stripe_secret: 'M0TrGI8bJB5gWUjvC7dYqvhzcfnuDt4K'
  stripe_public: 'pk_PwyeMrfgjrXzpjrX6JNw85WSWOcqB'
    
test:
  <<: *non_production_settings

production:
# stripe_keys:
#   Api_Secret = "xxx"
#   Api_Public = "xxx"